[4040][FIX] account_tax_round_down: Add signature
This PR addresses a TypeError(TypeError: _recompute_tax_lines() got an unexpected keyword argument 'tax_rep_lines_to_recompute') that was occurring when we try to validate account.move records, because there is mismatch in the method signature of the overridden _recompute_tax_lines method in a subclass.

The parent class method was expecting an additional argument tax_rep_lines_to_recompute, which was not accounted for in the subclass.